#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Hook Validator
 * Audits pre-commit hook chain for completeness and sequencing.
 */

export const EXPECTED_HOOKS = [
  'governance-check',
  'secret-scan',
  'retro-schema-check',
  'roadmap-validator',
];

const MERGED_SHIM_MARKER = 'merged-shim';

export function validateHookChain(hookPath, expectedHooks = EXPECTED_HOOKS) {
  const checks = [];
  let level = 'pass';
  const escalate = (next) => {
    if (next === 'error' || (next === 'warning' && level !== 'error')) level = next;
  };

  if (!fs.existsSync(hookPath)) {
    checks.push({
      name: 'Shim Completeness',
      level: 'error',
      message: 'Pre-commit hook file not found',
      details: [`Expected at: ${hookPath}`],
    });
    checks.push({
      name: 'Order-Independence',
      level: 'error',
      message: 'Cannot verify: hook file missing',
    });
    checks.push({
      name: 'Sequencing',
      level: 'error',
      message: 'Cannot verify: hook file missing',
    });
    return finalize(checks, 'error', expectedHooks);
  }

  const content = fs.readFileSync(hookPath, 'utf8');

  // Check 1: Shim Completeness
  const missing = expectedHooks.filter((hook) => !content.includes(hook));
  if (missing.length > 0) {
    checks.push({
      name: 'Shim Completeness',
      level: 'error',
      message: `Missing hooks in chain: ${missing.join(', ')}`,
      details: ['Re-run hook installer to restore merged shim'],
    });
    escalate('error');
  } else {
    checks.push({
      name: 'Shim Completeness',
      level: 'pass',
      message: `All ${expectedHooks.length} hooks present`,
    });
  }

  // Check 2: Order-Independence
  // We cannot actually re-run installers here; the only thing we can verify
  // statically is whether the shim carries the merged-shim marker that the
  // installer writes when it reconciles multiple installers into one file.
  // Without that marker we can't claim anything about independence — say so.
  if (content.includes(MERGED_SHIM_MARKER)) {
    checks.push({
      name: 'Order-Independence',
      level: 'pass',
      message: `Shim carries "${MERGED_SHIM_MARKER}" marker — generated by reconciling installer`,
    });
  } else {
    checks.push({
      name: 'Order-Independence',
      level: 'warning',
      message: `No "${MERGED_SHIM_MARKER}" marker found — cannot confirm this shim survives a second installer run`,
      details: ['Re-run the hook installer to regenerate a merged shim, or add the marker manually'],
    });
    escalate('warning');
  }

  // Check 3: Sequencing
  const positions = {};
  expectedHooks.forEach((hook) => {
    const pos = content.indexOf(hook);
    if (pos !== -1) positions[hook] = pos;
  });
  const sortedHooks = Object.entries(positions)
    .sort(([, a], [, b]) => a - b)
    .map(([hook]) => hook);
  const correctOrder = missing.length === 0 && expectedHooks.every((h, i) => sortedHooks[i] === h);

  if (missing.length > 0) {
    checks.push({
      name: 'Sequencing',
      level: 'warning',
      message: 'Cannot verify sequencing while hooks are missing from the chain',
    });
    escalate('warning');
  } else if (!correctOrder) {
    checks.push({
      name: 'Sequencing',
      level: 'warning',
      message: `Hooks execute in order: ${sortedHooks.join(' -> ')} (expected: ${expectedHooks.join(' -> ')})`,
      details: ['Reorder hooks or re-run installer'],
    });
    escalate('warning');
  } else {
    checks.push({
      name: 'Sequencing',
      level: 'pass',
      message: 'Hooks execute in correct order',
    });
  }

  return finalize(checks, level, expectedHooks);
}

function finalize(checks, level, expectedHooks) {
  let verdict = 'GREEN';
  if (level === 'error') verdict = 'RED';
  else if (level === 'warning') verdict = 'YELLOW';

  return {
    status: level === 'error' ? 'error' : 'success',
    verdict,
    checks,
    expectedHooks,
    timestamp: new Date().toISOString(),
  };
}

function printReport(output, verbose) {
  if (verbose) {
    console.log(JSON.stringify(output, null, 2));
    return;
  }
  output.checks.forEach((c) => {
    const icon = { pass: '✓', warning: '⚠', error: '❌' }[c.level];
    console.log(`${icon} ${c.name}: ${c.message}`);
    if (c.details) c.details.forEach((d) => console.log(`  -> ${d}`));
  });
  console.log(`\n${output.verdict} - Hook chain ${output.verdict === 'GREEN' ? 'is healthy' : 'has issues'}`);
}

function main() {
  const args = {
    hookPath: path.join(process.cwd(), '.git', 'hooks', 'pre-commit'),
    verbose: process.argv.includes('--verbose'),
    strict: process.argv.includes('--strict'),
  };

  const output = validateHookChain(args.hookPath);
  printReport(output, args.verbose);

  process.exit(
    output.verdict === 'GREEN' ? 0 :
    output.verdict === 'YELLOW' ? (args.strict ? 2 : 1) :
    2
  );
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1]);
if (isMain) main();
